<!-- detail -->
<template>
  <div class="detail">
    <div class="head">
      <img src="@/assets/left.png" alt="" @click="goback()">
    </div>
    <div class="content">
      <img v-for="(data,index) in info" :key="index" :src="data.src" alt="" :style={...data.styles} @click="showSwiper(index)">
    </div>
    <div class="foot">
      <div class="desc">点击查看大图</div>
      <div class="line"></div>
    </div>
    <div v-show="swiperFlag" class="myswiper">
      <div class="swiper-container">
        <div class="swiper-wrapper">
          <div class="swiper-slide" v-for="(data,index) in info" :key="'my'+index"><img :src="data.src" class="swiperImg"></div>
        </div>
      </div>
      <div><img src="@/assets/myclose.png" alt="" @click="closeSwiper()" class="closeimg"></div>
    </div>
  </div>
</template>

<script>
export default {
  data () {
    return {
      swiperFlag:false,
      mySwiper:null,
      userData:{
        user0:[
          {
            src:require('@/assets/imgs/1__1.jpg'),
            styles:{
              display:'inline-block',
              width:'406px',
              height:'273px',
              marginRight:'4px'
            }
          },
          {
            src:require('@/assets/imgs/1__2.jpg'),
            styles:{
              display:'inline-block',
              width:'184px',
              height:'273px',
            }
          },
          {
            src:require('@/assets/imgs/1__3.jpg'),
            styles:{
              display:'inline-block',
              width:'235px',
              height:'158px',
              marginRight:'8px'
            }
          },
          {
            src:require('@/assets/imgs/1__4.jpg'),
            styles:{
              display:'inline-block',
              width:'108px',
              height:'158px',
              marginRight:'8px'
            }
          },{
            src:require('@/assets/imgs/1__5.jpg'),
            styles:{
              display:'inline-block',
              width:'237px',
              height:'158px',
            }
          },{
            src:require('@/assets/imgs/1__6.jpg'),
            styles:{
              display:'inline-block',
              width:'296px',
              height:'197px',
              marginRight:'8px'
            }
          },{
            src:require('@/assets/imgs/1__7.jpg'),
            styles:{
              display:'inline-block',
              width:'294px',
              height:'197px'
            }
          },{
            src:require('@/assets/imgs/1__8.jpg'),
            styles:{
              float:'right',
              width:'396px',
              height:'269px'
            }
          },{
            src:require('@/assets/imgs/1__9.jpg'),
            styles:{
              float:'left',
              width:'194px',
              height:'129px',
              margin:'2px'
            }
          },{
            src:require('@/assets/imgs/1__10.jpg'),
            styles:{
              float:'left',
              width:'194px',
              height:'129px',
              margin:'2px'
            }
          }
        ],
        user1:[
          {
            src:require('@/assets/imgs/2__1.jpg'),
            styles:{
              float:'left',
              width:'340px',
              height:'226px',
              margin:'2px'
            }
          },
          {
            src:require('@/assets/imgs/2__2.jpg'),
            styles:{
              float:'right',
              width:'252px',
              height:'167px',
              margin:'2px'
            }
          },
          {
            src:require('@/assets/imgs/2__3.jpg'),
            styles:{
              float:'right',
              width:'252px',
              height:'167px',
              margin:'2px',
              marginBottom:'4px'
            }
          },
          {
            src:require('@/assets/imgs/2__4.jpg'),
            styles:{
              float:'left',
              width:'165px',
              height:'110px',
              margin:'2px'
            }
          },{
            src:require('@/assets/imgs/2__5.jpg'),
            styles:{
              float:'left',
              width:'165px',
              height:'110px',
              margin:'2px'
            }
          },{
            src:require('@/assets/imgs/2__6.jpg'),
            styles:{
              float:'left',
              width:'192px',
              height:'130px',
              margin:'2px'
            }
          },{
            src:require('@/assets/imgs/2__7.jpg'),
            styles:{
              float:'left',
              width:'193px',
              height:'130px',
              margin:'2px'
            }
          },{
            src:require('@/assets/imgs/2__8.jpg'),
            styles:{
              float:'right',
              width:'194px',
              height:'130px',
              margin:'2px'
            }
          },{
            src:require('@/assets/imgs/2__9.jpg'),
            styles:{
              float:'left',
              width:'600px',
              height:'400px',
              margin:'2px'
            }
          },{
            src:require('@/assets/imgs/2__10.jpg'),
            styles:{
              float:'left',
              width:'295px',
              height:'198px',
              margin:'2px'
            }
          },{
            src:require('@/assets/imgs/2__11.jpg'),
            styles:{
              float:'left',
              width:'297px',
              height:'198px',
              margin:'2px'
            }
          }
        ],
        user2:[
          {
            src:require('@/assets/imgs/3__1.jpg'),
            styles:{
              float:'left',
              width:'600px',
              height:'400px',
              margin:'2px'
            }
          },
          {
            src:require('@/assets/imgs/3__2.jpg'),
            styles:{
              float:'left',
              width:'345px',
              height:'515px',
              margin:'2px'
            }
          },
          {
            src:require('@/assets/imgs/3__3.jpg'),
            styles:{
              float:'left',
              width:'128px',
              height:'172px',
              margin:'2px'
            }
          },
          {
            src:require('@/assets/imgs/3__4.jpg'),
            styles:{
              float:'right',
              width:'115px',
              height:'153px',
              margin:'2px',
              marginBottom:'0px'
            }
          },{
            src:require('@/assets/imgs/3__5.jpg'),
            styles:{
              float:'left',
              width:'123px',
              height:'181px',
              margin:'2px'
            }
          },{
            src:require('@/assets/imgs/3__6.jpg'),
            styles:{
              float:'right',
              width:'116px',
              height:'176px',
              margin:'2px'
            }
          },{
            src:require('@/assets/imgs/3__7.jpg'),
            styles:{
              float:'left',
              width:'125px',
              height:'151px',
              margin:'2px'
            }
          },{
            src:require('@/assets/imgs/3__8.jpg'),
            styles:{
              float:'right',
              width:'116px',
              height:'155px',
              margin:'2px'
            }
          },{
            src:require('@/assets/imgs/3__9.jpg'),
            styles:{
              float:'left',
              width:'600px',
              height:'400px',
              margin:'2px'
            }
          }
        ],
        user3:[
          {
            src:require('@/assets/imgs/4__8.jpg'),
            styles:{
              float:'left',
              width:'173px',
              height:'355px',
              margin:'2px'
            }
          },
          {
            src:require('@/assets/imgs/4__1.jpg'),
            styles:{
              float:'right',
              width:'417px',
              height:'313px',
              margin:'2px'
            }
          },
          {
            src:require('@/assets/imgs/4__3.jpg'),
            styles:{
              float:'left',
              width:'206px',
              height:'272px',
              margin:'2px'
            }
          },
          {
            src:require('@/assets/imgs/4__2.jpg'),
            styles:{
              float:'right',
              width:'201px',
              height:'272px',
              margin:'2px',
            }
          },{
            src:require('@/assets/imgs/4__9.jpg'),
            styles:{
              float:'left',
              width:'173px',
              height:'345px',
              margin:'2px',
              marginTop:'-230px'
            }
          },{
            src:require('@/assets/imgs/4__4.jpg'),
            styles:{
              float:'left',
              width:'259px',
              height:'346px',
              margin:'2px'
            }
          },{
            src:require('@/assets/imgs/4__6.jpg'),
            styles:{
              float:'right',
              width:'146px',
              height:'109px',
              margin:'2px'
            }
          },{
            src:require('@/assets/imgs/4__5.jpg'),
            styles:{
              float:'right',
              width:'146px',
              height:'109px',
              margin:'2px'
            }
          },{
            src:require('@/assets/imgs/4__7.jpg'),
            styles:{
              float:'left',
              width:'146px',
              height:'109px',
              margin:'2px'
            }
          },
          {
            src:require('@/assets/imgs/4__10.jpg'),
            styles:{
              float:'left',
              width:'173px',
              height:'231px',
              margin:'2px',
              marginTop:'-230px'
            }
          }
        ],
        user4:[
          {
            src:require('@/assets/imgs/5__1.jpg'),
            styles:{
              float:'left',
              width:'290px',
              height:'435px',
              margin:'2px'
            }
          },
          {
            src:require('@/assets/imgs/5__2.jpg'),
            styles:{
              float:'right',
              width:'302px',
              height:'226px',
              margin:'2px',
              marginBottom:'6px'
            }
          },
          {
            src:require('@/assets/imgs/5__3.jpg'),
            styles:{
              float:'right',
              width:'301px',
              height:'201px',
              margin:'2px'
            }
          },
          {
            src:require('@/assets/imgs/5__4.jpg'),
            styles:{
              float:'left',
              width:'290px',
              height:'217px',
              margin:'2px',
            }
          },{
            src:require('@/assets/imgs/5__5.jpg'),
            styles:{
              float:'left',
              width:'145px',
              height:'218px',
              margin:'2px',
            }
          },{
            src:require('@/assets/imgs/5__6.jpg'),
            styles:{
              float:'left',
              width:'145px',
              height:'218px',
              margin:'2px'
            }
          },{
            src:require('@/assets/imgs/5__9.jpg'),
            styles:{
              float:'left',
              width:'113px',
              height:'170px',
              margin:'2px'
            }
          },{
            src:require('@/assets/imgs/5__8.jpg'),
            styles:{
              float:'left',
              width:'113px',
              height:'170px',
              margin:'2px',
              marginLeft:'-113px',
              marginTop:'175px'
            }
          },{
            src:require('@/assets/imgs/5__7.jpg'),
            styles:{
              float:'right',
              width:'472px',
              height:'353px',
              margin:'2px'
            }
          }
        ]
      }
    }
  },
  methods:{
    goback(){
      this.$router.go(-1)
    },
    showSwiper(index){
      this.swiperFlag=true;
      this.mySwiper.slideTo(index, 1000, false);
    },
    closeSwiper(){
      this.swiperFlag=false;
    }
  },
  computed:{
    info(){
      return this.userData[this.$route.params.index]
    }
  },
  mounted(){
    this.mySwiper = new Swiper('.swiper-container', {
      autoplay: true,
      observer: true,
      observeParents: true,
    })
  }
}
</script>

<style lang='scss' scoped>
  .detail{
    width:100%;
    overflow:scroll;
    position:relative;
    padding-bottom:100px;
    .head{
      padding:30px 75px;
    }
    .content{
      padding:0 75px;
    }
    .foot{
      width:80%;
      padding:30px 75px;
      .desc{
        font-size:18px;
        position:fixed;
        width:200px;
        left:280px;
        bottom:60px;
        color:#000;
        background: #fff;
        text-align:center;
        z-index:2;
      }
      .line{
        position:fixed;
        bottom:65px;
        width:80%;
        border-bottom:1px solid #C9C9C9;
      }
    }
    .myswiper{
      width:100%;
      position:absolute;
      top:0px;
      left:50%;
      height:100%;
      transform: translate(-50%);
      z-index:99;
      background:rgba(255,255,255,0.8);
      /* background:#fff; */
      .swiper-container{
        width:600px;
        height:1000px;
        border-bottom:2px solid #cdcdcd;
        .swiperImg{
          width:600px;
          /* height:400px; */
          margin:50% 50%;
          transform: translate(-50%,-50%);
          display:inline-block;
          padding-top:400px;
        }
      }
      .closeimg{
        position:fixed;
        top:970px;
        left:50%;
        z-index:9999;
        transform: translate(-50%);
      }
    }
  }
</style>
